### PR TITLE
Rename OsPlaybookGenerator to OsConfigGenerator

### PR DESCRIPTION
**Pull request by dprince**
This should better align our CR names with 'ConfigDownload'.

OSPK8-401 #close Closing issue.

### CODE REVIEW

**Review by stuggi — COMMENTED** [review]
lgtm, but we'd also need a dev-tools change for that [1]

[1] https://github.com/openstack-k8s-operators/osp-director-dev-tools/blob/master/ansible/templates/osp/playbook_generator/openstackplaybookgenerator.yaml.j2

**Comment by dprince** [comment]
> lgtm, but we'd also need a dev-tools change for that [1]
> 
> [1] https://github.com/openstack-k8s-operators/osp-director-dev-tools/blob/master/ansible/templates/osp/playbook_generator/openstackplaybookgenerator.yaml.j2

I have it done just need to push it. Waiting for tests to finish...

**Comment by dprince** [comment]
> lgtm, but we'd also need a dev-tools change for that [1]
> 
> [1] https://github.com/openstack-k8s-operators/osp-director-dev-tools/blob/master/ansible/templates/osp/playbook_generator/openstackplaybookgenerator.yaml.j2

https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/267

**Review by stuggi — APPROVED** [review]
/lgtm

**Review by abays — APPROVED** [review]
Looks good to me as well.  We should probably merge this one soon so @stuggi can then rebase https://github.com/openstack-k8s-operators/osp-director-operator/pull/457 (which also touches some of the same files)

**Pull request merged**
